### ISSUE TITLE
I want change scale center to left , but some problem

### ISSUE THREAD

**Issue by susuyan** [jVirus/uicollectionview-layouts-kit#6]
![61178444-b4dba000-a61f-11e9-92f4-b63dc91031ec](https://user-images.githubusercontent.com/7692197/61196912-5b00d600-a704-11e9-9595-544fcbc63684.png)
```
private func configureAttributes(for attributes: UICollectionViewLayoutAttributes) {
    guard let collection = collectionView else { return }
    var visibleRect = CGRect()
    visibleRect.origin = collection.contentOffset
    visibleRect.size = collection.bounds.size
    let collectionLeft =  itemSize.width / 2
    let offset = collection.contentOffset.x
    let normalizedLeft =  attributes.center.x  - offset

    let maxDistance =  self.itemSize.width
    let distance = min(abs(collectionLeft - normalizedLeft), maxDistance)
    let ratio = (maxDistance - distance)/maxDistance
    let scale = ratio * (1 - sideItemScale) + sideItemScale

    var t = CATransform3DIdentity
    t = CATransform3DScale(t,  scale, scale, 1.0)
    attributes.zIndex = Int(scale * 10)
    attributes.transform3D = t
    //  change item space,  

}
```

**Comment by jVirus** [comment]
Hello,

As far as I can see, your question isn't directly related to any of the developments presented in this repository. This is just a quick note for people, who read this issue thread.

In order to make the spacings equal, even between the cells that have different sizes, you need to take into account the following things:

1. Cell's insets
2. Your calculations need to be done with respect to the cell's right or left edge, rather than the center of a cell (it seems like already do that, by computing the normalized left offset)
3. If applying affine transformations, they need to be done uniformly, and respect the cells' sizes
4. Configuration that may be done outside of the custom layout

In your method that computes custom attributes for `UICollectionViewLayout` the issue may lie in code that does affine transformations. I can't tell you more, since I need to reproduce the issue and have the full source code to the your custom layout class, in order to debug and see what is actually going on inside your development. 

I suggest you to use debugger, take a look at cells' properties, such as: `frame`, `affine transformation` and `insets`.

Thanks for the question, I hope it will help you figure out the exact spot in your layout that needs fixes.
