### ISSUE TITLE
Clarify setup?

### ISSUE THREAD

**Issue by anohren** [jVirus/uicollectionview-layouts-kit#7]
I tried following the setup and usage instructions in the readme for the circular layout, which was basically

1. Copy the contents of the `Layout` directory
2. Wire up the layout class to the controller in storyboard

The part of the instructions I did not undestand was

> In your view controller you need to provide a valid reference to the UIViewController from Storyboard/Nib file where you overriden the default layout class.

A valid reference in the controller to itself? How about `self`? 🙂

Anyway, I changed `itemSize` just to show what kind of stack I end up with

![Skärmavbild 2020-06-03 kl  15 37 13](https://user-images.githubusercontent.com/3519879/83643418-480f2280-a5b0-11ea-8470-9432ff4df39c.png)

What else does it require?

**Comment by jVirus** [comment]
If you didn't understand something, if you didn't like the way the ***self referencing*** was formulated, or if something is not working the way you expected, there is no need to make the whole issue toxic. Please, note that for the next time 😉.

Since the layout transforms `UICollectionViewLayoutAttributes` for each `UICollectionViewCell`, you need to supply a custom implementation for `UICollectionViewCell` and override the `apply(_ layoutAttributes:)` method. For example:

```swift
override func apply(_ layoutAttributes: UICollectionViewLayoutAttributes) {
        super.apply(layoutAttributes)
        
        // Since anchor point is a custom propertiy, it needs to be manually applied here, in a subclass. 
        
        guard let circularLayoutAttributes = layoutAttributes as? CircularCollectionViewLayoutAttributes else {
            debugPrint(#function + " could not cast UICollectionViewLayoutAttribures to CircularCollectionViewLayoutAttribures, the execution of the method will be aborted")
            return
        }
        self.layer.anchorPoint = circularLayoutAttributes.anchorPoint
        self.center.y += (circularLayoutAttributes.anchorPoint.y - 0.5) * self.bounds.height
}
```

Again, please, before submitting an issue, make sure you understand that an Open Source project may not be perfect and people who originally created it, gave you a "free" software or a piece of it, so they also may not be able to help you. Especially when a request is done in a sarcastic manner and objectively points out some silly things.  

Thank you, I hope it helps.

**Comment by jVirus** [comment]
If you didn't understand something, if you didn't like the way the ***self referencing*** was formulated, or if something is not working the way you expected, there is no need to make the whole issue toxic by making some sarcastic comments. Please, note that for the next time 😉.

Since, the layout transforms `UICollectionViewLayoutAttributes` for each `UICollectionViewCell`, you need to supply a custom implementation for `UICollectionViewCell` and override the `apply(_ layoutAttributes:)` method. For example:

```swift
override func apply(_ layoutAttributes: UICollectionViewLayoutAttributes) {
        super.apply(layoutAttributes)
        
        // Since anchor point is a custom propertiy, it needs to be manually applied here, in a subclass. 
        
        guard let circularLayoutAttributes = layoutAttributes as? CircularCollectionViewLayoutAttributes else {
            debugPrint(#function + " could not cast UICollectionViewLayoutAttribures to CircularCollectionViewLayoutAttribures, the execution of the method will be aborted")
            return
        }
        self.layer.anchorPoint = circularLayoutAttributes.anchorPoint
        self.center.y += (circularLayoutAttributes.anchorPoint.y - 0.5) * self.bounds.height
}
```

I recommend you to dive deeper into the official docs, where you find a lot of answers and more thought understanding of the features that [UICollectionView](https://developer.apple.com/documentation/uikit/uicollectionview) has.

Thank you, I hope it helps.

**Comment by anohren** [comment]
> there is no need to make the whole issue toxic by making some sarcastic comments. Please, note that for the next time 😉.

It was a friendly joke while trying to convey how I understood the sentence, so that you could determine whether I had misunderstood it or not. No offense intended. But you are of course free to project any preconceived notion of intent and toxicity on it if you wish. 

Thanks for the clarification!

**Comment by jVirus** [comment]
No preconceived notion projected, it was not clear for me whether it's, as you just clarified a friendly joke, or a toxic sarcastic comment. I only had an intention to make the dialog comfortable for everyone, not just an initial commentator. 

You are welcome!

**Comment by anohren** [comment]
Thanks for your reply. I'll try to be less ambiguous in the future.
